# Generated by Django 3.2 on 2024-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20240215_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
