# Generated by Django 3.2 on 2024-02-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0004_auto_20240215_1828'),
        ('base', '0002_actionhistory_companyhistory_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
    ]
