# Generated by Django 3.2 on 2024-02-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20240215_1828'),
        ('company', '0001_initial'),
        ('base', '0003_auto_20240216_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhistory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_history', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_history', to='employee.employee'),
        ),
    ]
