# Generated by Django 3.2 on 2024-02-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20240216_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehistory',
            name='actionhistory_ptr',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CompanyHistory',
        ),
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
    ]
