# Generated by Django 3.2 on 2024-02-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('base', '0005_auto_20240216_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_history', to='company.company')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionHistory',
        ),
    ]
