# Generated by Django 3.2 on 2024-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20240216_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyactionhistory',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
