# Generated by Django 3.2 on 2024-02-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_companyactionhistory_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyactionhistory',
            name='company',
        ),
    ]
