# Generated by Django 3.2 on 2024-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_companyactionhistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyactionhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
