# Generated by Django 3.2 on 2024-02-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_companyactionhistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
